### ISSUE TITLE
Lua5.2/Lua5.3 compatibility

### ISSUE THREAD

**Issue by msva** [mkottman/ltn12ce#4]
```
src/ltn12ce_comp_zlib.c: In function ‘init_comp_zlib’:
src/ltn12ce_comp_zlib.c:184:5: warning: implicit declaration of function ‘luaL_register’ [-Wimplicit-function-declaration]
     luaL_register(L, NULL, module_functions);
     ^
make[2]: *** [src/CMakeFiles/ltn12ce_core.dir/build.make:183: src/CMakeFiles/ltn12ce_core.dir/ltn12ce_comp_zlib.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/ltn12ce_comp_bzip2.c: In function ‘init_comp_bzip2’:
src/ltn12ce_comp_bzip2.c:195:5: warning: implicit declaration of function ‘luaL_register’ [-Wimplicit-function-declaration]
     luaL_register(L, NULL, module_functions);
     ^
src/ltn12ce_comp_lzma.c: In function ‘init_comp_lzma’:
src/ltn12ce_comp_lzma.c:181:5: warning: implicit declaration of function ‘luaL_register’ [-Wimplicit-function-declaration]
     luaL_register(L, NULL, module_functions);
     ^
```

ref: http://lua.2524044.n2.nabble.com/Why-did-luaL-openlib-luaL-register-go-td7649023.html
One of the way to fix:
https://github.com/msva/luaxml/blob/master/LuaXML_lib.c#L53
+
https://github.com/msva/luaxml/blob/master/LuaXML_lib.c#L441

or:
https://github.com/brimworks/lua-zlib/blob/master/lua_zlib.c#L11-L16 (less preferred, since still keeps it in global space in 5.1, which is a bad practice)
